CREATE TABLE "premade_message_templates" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"content" text NOT NULL,
	"target_roles" text,
	"is_system_template" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "premade_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "premade_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"template_id" text NOT NULL,
	"project_id" integer NOT NULL,
	"author_agent_id" text NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN "git_origin" text;--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN "main_branch" text DEFAULT 'main';--> statement-breakpoint
ALTER TABLE "prompts" ADD COLUMN "is_role_prompt" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "premade_messages" ADD CONSTRAINT "premade_messages_template_id_premade_message_templates_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."premade_message_templates"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "premade_messages" ADD CONSTRAINT "premade_messages_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "premade_messages" ADD CONSTRAINT "premade_messages_author_agent_id_agents_id_fk" FOREIGN KEY ("author_agent_id") REFERENCES "public"."agents"("id") ON DELETE no action ON UPDATE no action;