-- Fix role foreign keys and add milestones table

-- Drop roleType columns and add/fix roleId foreign keys
ALTER TABLE "vacancies" DROP COLUMN IF EXISTS "role_type";--> statement-breakpoint
ALTER TABLE "vacancies" ADD COLUMN "role_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "agents" DROP COLUMN IF EXISTS "role_type";--> statement-breakpoint  
ALTER TABLE "agents" ALTER COLUMN "role_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "role_assignments" DROP COLUMN IF EXISTS "role_type";--> statement-breakpoint
ALTER TABLE "role_assignments" ADD COLUMN "role_id" integer NOT NULL;--> statement-breakpoint

-- Rename assignedToRole columns to use foreign keys
ALTER TABLE "content" RENAME COLUMN "assigned_to_role" TO "assigned_to_role_id";--> statement-breakpoint
ALTER TABLE "content" ALTER COLUMN "assigned_to_role_id" TYPE integer USING assigned_to_role_id::integer;--> statement-breakpoint
ALTER TABLE "tasks" RENAME COLUMN "assigned_to_role" TO "assigned_to_role_id";--> statement-breakpoint
ALTER TABLE "tasks" ALTER COLUMN "assigned_to_role_id" TYPE integer USING assigned_to_role_id::integer;--> statement-breakpoint

-- Create milestones table
CREATE TABLE "milestones" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "milestones_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"role_id" integer NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"prompt" text NOT NULL,
	"required_inputs" text,
	"expected_outputs" text,
	"order_index" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"success_criteria" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);--> statement-breakpoint

-- Add foreign key constraints
ALTER TABLE "vacancies" ADD CONSTRAINT "vacancies_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_assignments" ADD CONSTRAINT "role_assignments_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content" ADD CONSTRAINT "content_assigned_to_role_id_roles_id_fk" FOREIGN KEY ("assigned_to_role_id") REFERENCES "roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_assigned_to_role_id_roles_id_fk" FOREIGN KEY ("assigned_to_role_id") REFERENCES "roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestones" ADD CONSTRAINT "milestones_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestones" ADD CONSTRAINT "milestones_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE no action ON UPDATE no action;